version: '3.8'

services:
  postgres:
    image: postgres:14.0-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - backend_nw

  api:
    image: ${DOCKERHUB_USERNAME}/final_work:latest
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
    depends_on:
      - postgres
    networks:
      - backend_nw
      - frontend

  frontend:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
    networks:
      - frontend

  bot:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_BOT_TOKEN}
      POSTGRES_HOST: postgres
    command: python manage.py runbot
    depends_on:
      - postgres
    networks:
      - backend_nw

volumes:
  postgres_data:

networks:
  backend_nw:
    driver: bridge
  frontend:
    driver: bridge